version: '3.8'

services:
  backend:
    build: .
    container_name: flask-api
    ports:
      - "5000:5000"
  
  frontend:
    build: ./frontend
    container_name: resource-ui
    ports:
      - "8080:80"
    depends_on:
      - backend
